services:
  mongo:
    image: mongo:8.0
    container_name: delfos-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - delfos_mongo_data:/data/db

volumes:
  delfos_mongo_data:
