/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AuditLogs {
  action: string;
  actor_user_id: string | null;
  created_at: Generated<Timestamp>;
  entity: string;
  entity_id: string | null;
  id: Generated<string>;
  metadata: Generated<Json>;
  tenant_id: string;
}

export interface Connections {
  allowed_headers: Generated<Json>;
  auth_type: Generated<string>;
  base_url: string;
  created_at: Generated<Timestamp>;
  credential_ref: string | null;
  id: Generated<string>;
  metadata: Generated<Json>;
  name: string;
  status: Generated<string>;
  tenant_id: string;
  type: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface Credentials {
  connection_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  masked_preview: string | null;
  name: string;
  protected_secret_value: string;
  protection_provider: string;
  provider: string | null;
  revoked_at: Timestamp | null;
  rotated_at: Timestamp | null;
  status: Generated<string>;
  tenant_id: string;
  type: string;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface DashboardDefinitions {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  dashboard_key: string;
  description: string | null;
  filters: Generated<Json>;
  id: Generated<string>;
  layout: Generated<Json>;
  metadata: Generated<Json>;
  name: string;
  sections: Generated<Json>;
  settings: Generated<Json>;
  status: Generated<string>;
  tags: Generated<Json>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  visibility: Generated<string>;
  widgets: Generated<Json>;
}

export interface Datasets {
  connection_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  dataset_key: string;
  description: string | null;
  fields: Generated<Json>;
  id: Generated<string>;
  metadata: Generated<Json>;
  name: string;
  primary_key_fields: Generated<Json>;
  refresh_mode: Generated<string>;
  schema_mode: Generated<string>;
  settings: Generated<Json>;
  source_type: Generated<string>;
  status: Generated<string>;
  tags: Generated<Json>;
  tenant_id: string;
  time_field: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface ExecutionRequestEvents {
  actor_id: string | null;
  actor_role: string | null;
  created_at: Generated<Timestamp>;
  event_type: string;
  execution_request_id: string;
  id: Generated<string>;
  message: string | null;
  metadata: Generated<Json>;
  next_status: string | null;
  previous_status: string | null;
  reason: string | null;
  request_key: string;
  tenant_id: string;
}

export interface ExecutionRequests {
  connection_id: string | null;
  created_at: Generated<Timestamp>;
  dashboard_definition_id: string | null;
  dataset_id: string | null;
  id: Generated<string>;
  kind: string;
  message: string | null;
  metadata: Generated<Json>;
  mode: Generated<string>;
  query_definition_id: string | null;
  reason: string | null;
  report_definition_id: string | null;
  request_key: string;
  requested_by_actor_id: string | null;
  requested_by_role: string | null;
  status: Generated<string>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface FieldMappings {
  connection_id: string | null;
  created_at: Generated<Timestamp>;
  dataset_key: string;
  id: Generated<string>;
  required: Generated<boolean>;
  source_path: string;
  status: Generated<string>;
  target_field: string;
  target_type: string;
  tenant_id: string;
  transform: string | null;
  updated_at: Generated<Timestamp>;
}

export interface QueryDefinitions {
  allowed_granularities: Generated<Json>;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  dataset_id: string;
  default_limit: number | null;
  description: string | null;
  dimensions: Generated<Json>;
  filters: Generated<Json>;
  id: Generated<string>;
  metadata: Generated<Json>;
  metrics: Generated<Json>;
  name: string;
  query_key: string;
  settings: Generated<Json>;
  sorts: Generated<Json>;
  status: Generated<string>;
  tags: Generated<Json>;
  tenant_id: string;
  time_field: string | null;
  type: Generated<string>;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface ReportDefinitions {
  blocks: Generated<Json>;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  dashboard_definition_id: string | null;
  description: string | null;
  export_options: Generated<Json>;
  filters: Generated<Json>;
  id: Generated<string>;
  layout: Generated<Json>;
  metadata: Generated<Json>;
  name: string;
  parameters: Generated<Json>;
  query_definition_id: string | null;
  report_key: string;
  sections: Generated<Json>;
  settings: Generated<Json>;
  status: Generated<string>;
  tags: Generated<Json>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  visibility: Generated<string>;
}

export interface SemanticModels {
  certification_owner: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  dataset_keys: Generated<Json>;
  description: string | null;
  dimensions: Generated<Json>;
  glossary_terms: Generated<Json>;
  id: Generated<string>;
  measures: Generated<Json>;
  metadata: Generated<Json>;
  model_key: string;
  name: string;
  owner: string | null;
  quality: Generated<Json>;
  settings: Generated<Json>;
  status: Generated<string>;
  steward: string | null;
  tags: Generated<Json>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface Tenants {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  settings: Generated<Json>;
  slug: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface Users {
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
  name: string;
  role: Generated<string>;
  status: Generated<string>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  audit_logs: AuditLogs;
  connections: Connections;
  credentials: Credentials;
  dashboard_definitions: DashboardDefinitions;
  datasets: Datasets;
  execution_request_events: ExecutionRequestEvents;
  execution_requests: ExecutionRequests;
  field_mappings: FieldMappings;
  query_definitions: QueryDefinitions;
  report_definitions: ReportDefinitions;
  semantic_models: SemanticModels;
  tenants: Tenants;
  users: Users;
}
